---
title: "Curriculum Vitae"
---

::: {.content-card}
Download a copy of my [CV here](https://drive.google.com/file/d/1YoCzzaly8yEfzAXzA7QCf0Iw8nGdfp8B/view?usp=drive_link).  
:::

::: {.content-card}
## Education

- **2020: PhD** - University of Hawaiʻi at Mānoa (UHM), Marine Biology Graduate Program, Hawaiʻi Institute of Marine Biology (HIMB)

- **2014: Bachelor of Science** - Oregon State University (OSU), Honors Biology, Marine Focus, Chemistry Minor 
:::

::: {.content-card}
## Professional Experience

- **2024-present: Research Scientist** (University of Washington)
- **2020-2024: Postdoctoral Researcher** (University of Washington, University of Rhode Island)
  - National Science Foundation Ocean Sciences Postdoctoral Fellow (2022-2024)
  - UW eScience Data Science Postdoctoral Fellow (2022-2024)
- **2014-2020: Graduate Research and Teaching Assistant** (University of Hawaiʻi at Mānoa) 
:::

::: {.content-card}
## Publications

1. Baird M, **AS Huffmyer**, N Ozguner, SB Roberts. Parental immune priming reshapes offspring growth, metabolism, and thermal tolerance in the Pacific Oyster. [Read on bioRxiv here.](https://doi.org/10.64898/2025.12.10.693539)  
2. **Huffmyer AS**, et al. Seasonal plasticity of symbiotic strategies clarifies coral holobiont resistance and resilience. *In review*. *Ecology and Evolution*. [Read on bioRxiv here.](https://doi.org/10.1101/2025.11.20.689604) 
3. **Huffmyer AS**, N Ozguner, M Baird, C Elvrum, C Kounellas, D Dicksion, SJ White, L Plough, MR Gavery, N Krebs, W Walton, J Small, M Pitsenbarger, H Ealy-Whitfield, S Roberts. From blue to pink: Resazurin as a high-throughput proxy for metabolic rate in oysters. *In review*. *PeerJ*. [Read on bioRxiv here.](http://doi.org/10.1101/2025.11.06.686367) 
4. Ashey J, JA Rodriquez-Casariego, KM Durkin, Z Bengtsson, **AS Huffmyer**, SJ White, DM Becker, JM Eirin-Lopez, HM Putnam, S Roberts. Non-coding RNA repertoire in reef-building corals. *In review*. *Environmental Epigenetics*. [Read on bioRxiv here.](https://doi.org/10.1101/2025.03.15.643469)  
5. Gorman LM, **AS Huffmyer**, M Byrne, SC Mills, HM Putnam. Coral venom and toxins as protection against crown-of-thorns sea star attack. *Molecular Ecology* 35:e70202. [Read here.](https://doi.org/10.1111/mec.70202) 
6. Ashey J, F Scucchia, **AS Huffmyer**, HM Putnam, T Mass. 2025. Thermal and acidification gradients reveal tolerance thresholds in *Pocillopora acuta* recruits. *Molecular Ecology* 34:e70116. [Read here.](https://doi.org/10.1111/mec.70116) 
7. Venkataraman Y and **AS Huffmyer**. 2025. Interrogating metabolic plasticity in marine organisms: A framework for best practices using metabolomic and lipidomic approaches. *Integrative and Comparative Biology*. 65:1166-1184. [Read here.](https://doi.org/10.1093/icb/icaf138) 
8. **Huffmyer AS**, KH Wong, DM Becker, E Strand, T Mass, HM Putnam. 2025. Shifts and critical periods in coral metabolism reveal energetic vulnerability during development. *Current Biology* 35: 2858-2871. [Read here.](https://doi.org/10.1016/j.cub.2025.05.013) 
9. **Huffmyer AS**, J Ashey, E Strand, E Chiles, X Su, HM Putnam. 2024. Coral larvae increase nitrogen assimilation to stabilize algal symbiosis and combat bleaching under increased temperature. *PLoS Biology* 22: e3002875. [Read here.](https://doi.org/10.1371/journal.pbio.3002875) 
10. Venkataraman YR, **AS Huffmyer**, SJ White, A Downey-Wall, J Ashey, DM Becker, Z Bengtsson, HM Putnam, E Strand, JA Rodríguez-Casariego, SA Wanamaker, KE Lotterhos, SB Roberts. 2024. DNA methylation correlates with transcriptional noise in response to elevated pCO2 in the eastern oyster (*Crassostrea virginica*). *Environmental Epigenetics* 10: dvae018. [Read here.](https://doi.org/10.1093/eep/dvae018)
11. Chiles EN, **AS Huffmyer**, C Drury, HM Putnam, D Bhattacharya, X Su. 2023. Stable isotope tracing reveals compartmentalized nitrogen assimilation in scleractinian corals. *Frontiers in Marine Science* 9: 1035523. [Read here.](https://doi.org/10.3389/fmars.2022.1035523)  
12. **Huffmyer AS**, E Majerova, N Bean, C Harris, C Drury. 2022. Variable intraspecific diversity effects impact thermal tolerance in a reef-building coral. *Coral Reefs* 42:119-129. [Read here.](https://doi.org/10.1007/s00338-022-02320-0)  
13. **Huffmyer AS**, T O’Neill, JD Lemus. 2022. Evidence for professional conceptualization in science as an important component of science identity. *CBE – Life Sciences Education* 21(4): ar76. [Read here.](https://doi.org/10.1187/cbe.20-12-0280)   
14. Alexander G, J Hancock, **AS Huffmyer**, SB Matsuda. 2022. Larval thermal pre-exposure does not improve post-settlement thermal tolerance in a dominant reef-building coral, *Montipora capitata*. *Coral Reefs* 41:333-342. [Read here.](https://doi.org/10.1007/s00338-022-02234-x)  
15. Matsuda SB, LJ Chakravarti, R Cunning, **AS Huffmyer**, CE Nelson, RD Gates, MJH van Oppen. 2022. Temperature mediated acquisition of rare heterologous symbionts promotes survival of coral larvae under ocean warming. *Global Change Biology* 28:2006-2025. [Read here.](https://doi.org/10.1111/gcb.16057)   
16. **Huffmyer AS**, CJ Johnson, AM Epps, JD Lemus, RD Gates. 2021. Feeding and thermal conditioning enhance coral temperature tolerance in juvenile *Pocillopora acuta*. *Royal Society Open Science* 8: 210644. [Read here.](https://doi.org/10.1098/rsos.210644) 
17. Barott KL, **AS Huffmyer**, J Davidson, EA Lenz, SB Matsuda, J Hancock, T Innis, B Glazer, C Drury, H Putnam, RD Gates. 2021. Coral bleaching response is unaltered following acclimatization to reefs with distinct environmental conditions. *PNAS* 118: e2025435118. [Read here.](https://doi.org/10.1073/pnas.2025435118) 
18. Innis T, L Allen-Waller, KT Brown, W Sparagon, C Carlson, E Kruse, **AS Huffmyer**, CE Nelson, HM Putnam, KL Barott. 2021. Marine heatwaves depress metabolic activity and impair cellular acid-base homeostasis in reef-building corals regardless of bleaching susceptibility. *Global Change Biology* 27: 2728-2743. [Read here.](https://doi.org/10.1111/gcb.15622) 
19. **Huffmyer AS**, C Drury, E Majerová, JD Lemus, RD Gates. 2021. Tissue fusion and enhanced genotypic diversity support survival of juvenile *Pocillopora acuta* corals under thermal stress. *Coral Reefs* 40: 447-458. [Read here.](https://doi.org/10.1007/s00338-021-02074-1) 
20. Roach TNF, S Yadav, C Caruso, J Dilworth, CM Foley, JR Hancock, J Huckeba, **AS Huffmyer**, K Hughes, VA Kahkejian, EMP Madin, SB Matsuda, M McWilliam, S Miller, EP Santoro, M Rocha de Souza, D Torres-Pulliza, C Drury, JS Madin. 2021. A field primer for monitoring benthic ecosystems using structure-from-motion photogrammetry. *Journal of Visualized Experiments*. 170: e61815. [Read here.](https://www.jove.com/v/61815/a-field-primer-for-monitoring-benthic-ecosystems-using-structure-from) 
21. Hancock J, A Barrows, T Roome, **AS Huffmyer**, SB Matsuda, S Rahnke, N Munk, C Drury. 2021. Coral husbandry for ocean futures: leveraging abiotic factors to increase survivorship, growth, and resilience in juvenile *Montipora capitata*. *Marine Ecology Progress Series* 657:123-133. [Read here.](https://doi.org/10.3354/meps13534) 
22. Matsuda S, **AS Huffmyer**, EA Lenz, J Davidson, J Hancock, A Przybylowski, T Innis, RD Gates, KL Barott. 2020. Coral bleaching susceptibility is predictive of subsequent mortality within but not between coral species. *Frontiers in Ecology and Evolution* 8:178. [Read here.](https://doi.org/10.3389/fevo.2020.00178) 
23. **Huffmyer AS**, SB Matsuda, AE Eggers, JD Lemus, RD Gates. 2020. Evaluation of laser scanning confocal microscopy as a method for characterizing reef-building coral tissue thickness and Symbiodiniaceae fluorescence. *Journal of Experimental Biology* 223: jeb220335. [Read here.](https://doi.org/10.1242/jeb.220335) 
24. **Huffmyer AS** and JD Lemus. 2019. Graduate TA teaching styles impact student achievement in a research-based undergraduate science course. *Journal of College Science Teaching* 48:56-65. [Read here.](https://www.jstor.org/stable/26901283)
25. **Meltvedt AM** and C Jadot. 2014. Progression of the coral – algal phase shift in the Caribbean: a case study in Bonaire, Dutch Caribbean. *Marine Technology Society Journal*: 48:33-41. [Read here.](https://doi.org/10.4031/MTSJ.48.6.4)

:::

::: {.content-card}
## Awards & Honors

#### Postdoctoral Funding and Awards 

- **National Science Foundation Ocean Sciences Postdoctoral Fellowship** - 2022-2024
- **University of Washington eScience Institute Postdoctoral Grants** - 2022-2024
- **Journal of Experimental Biology Traveling Fellowship** - 2024
- **University of Washington Data Science Postdoctoral Fellowship** - 2022-2024

#### Graduate Funding and Awards 

- **National Science Foundation Graduate Research Fellowship** - 2016-2019
- **PEO National Scholar	 Award, Mary Louise Remy Endowed Scholar** - 2018-2019
- **Hawaiʻi Institute of Marine Biology Lord Scholarship Fund Awards** - 2016-2019	
- **University of Hawaiʻi at Mānoa Opportunity Grants** - 2014-2018
- **University of Hawaiʻi at Mānoa Graduate Student Organization Award** - 2019
- **University of Hawaiʻi at Mānoa Edmondson Grant Awards** - 2017-2019
- **Best Graduate Paper, UHM Mānoa Tester Symposium** - 2018

#### Undergraduate Funding and Awards 

- **Magna Cum Laude (3.82 GPA)** - 2014
- **Waldo Cummings Outstanding Undergraduate Student Awards** - 2011-2014
- **National Oceanic and Atmospheric Admin. Ernest Hollings Scholarship** - 2012-2014
- **Academic and Community Undergraduate Scholarship Awards** - 2010-2014 
:::

::: {.content-card}
## Presentations 

View my public presentations on [GitHub here.](https://github.com/AHuffmyer/presentations/tree/master)

#### Oral Presentations  

1. **Huffmyer AS**, P Harnay, E Chiles, C Gilligan, L Gorman, S Roberts, HM Putnam. Diverse nutritional strategies mediate early life thermal responses in reef-building corals in Moorea. Moorea Coral Reef Long Term Ecological Research All-Investigators Meeting. Virtual. December 2025.  
2. **Huffmyer AS** et al. Stress hardening and metabolic screening: Tools to assess oyster performance and resilience. Pacific Coast Shellfish Growers Association Conference. Vancouver, WA, USA. September 2025. 
3. **Huffmyer AS** et al. Holobiont composition and seasonal plasticity in physiology are key to understanding reef building coral resilience. Moorea Coral Reef Long Term Ecological Research All-Investigators Meeting. Virtual. December 2024.  
4. **Huffmyer AS**. Seasonal environmental variation drives host and symbiont physiological state of three important reef-building coral species in Moorea, French Polynesia. University of Washington eScience Postdoctoral Fellows seminar. Seattle, WA, USA. January 2024.  
5. **Huffmyer AS**, J Ashey, E Chiles, E Strand, X Su, HM Putnam. Thermal stress reduces photosynthate metabolism and disrupts nitrogen cycling in coral larvae. Society of Integrative and Comparative Biology. Seattle, WA, USA. January 2024.  
6. **Huffmyer AS**. Metabolic dysfunction of the coral-algal symbiosis under marine heatwaves: Insights from a stable isotope metabolomic approach. University of Washington eScience Postdoctoral Fellows seminar. Seattle, WA, USA. May 2023.  
7. **Huffmyer AS**. Multi-omic approaches to understand reef coral development and symbiosis. University of Washington eScience Postdoctoral Fellows seminar. Seattle, WA, USA. November 2022.  
8. **Huffmyer AS**, K Wong, DM Becker-Polinski, E Strand, T Mass, HM Putnam. Physiological and multi-omic signatures of shifts in symbiotic nutritional exchange in reef-building coral early life history. Benthic Ecology Conference. Portsmouth, NH, USA. March 2022.
9. **Huffmyer AS**. How do dynamic environmental conditions shape coral symbiosis and metabolism and drive energetic-epigenetic linkages? Moorea Coral Reef LTER All Investigators Meeting. Virtual presentation. November 2021. 
10. **Huffmyer AS**, T O’Neill, JD Lemus. Supporting professional science identity for science students. STEMS2 Symposium. Virtual presentation. June 2020.
11. **Huffmyer AS**. Getting a head start: Influential early experiences for juvenile corals and science students. PhD Defense. University of Hawaiʻi at Mānoa. Honolulu, HI, USA. January 2020.
12. **Huffmyer AS**. Conditioning and physiological flexibility in juvenile corals. Coral Assisted Evolution Symposium. Australian Institute of Marine Science, Queensland, Australia. May 2019.
13. **Huffmyer AS** and RD Gates. Getting a head start: Thermal and nutritional conditioning of juvenile corals. UHM Albert L. Tester Symposium. Honolulu, HI, USA. April 2018.
14. **Huffmyer AS** and RD Gates. Getting a head start: Thermal and nutritional conditioning of juvenile corals. Society of Integrative and Comparative Biology. San Francisco, CA, USA. January 2018.
15. **Huffmyer AS**, H Putnam, RD Gates. Parental influence on growth and survivorship of juvenile Pocillopora damicornis corals exposed to increased temperature. American Society of Limnology and Oceanography. Honolulu, HI, USA. February 2017.
16. **Huffmyer AS** and J Lemus. TA teaching styles impact student achievement in a research-based undergraduate science course. UHM Albert L. Tester Symposium. Honolulu, HI, USA. April 2016.
17. **Meltvedt AM**. Population structure and genetic variation in the Hawaiian Opakapaka (Pristipomoides filamentosus): Evidence of a genetic bottleneck in offspring of a captive broodstock. Undergraduate Thesis Defense. Corvallis, OR, USA. May 2014.
18. **Meltvedt AM**. Increasing literacy in marine science: A summer education program for Hawaiʻi high school students. NOAA Hollings Scholar Symposium. August 2013. Silver Springs, MD, USA.
19. **Meltvedt AM**, K Beem, A Carsh. Site and light: factors affecting growth rates of Saccharina sessilis kelp. Hatfield Marine Science Student Symposium. Newport, OR, USA. June 2013.
20. **Meltvedt AM**. Reef health at Yellow Sub, Bonaire: progression of a coral-algal phase shift. CIEE Student Research Symposium. Bonaire, Dutch Caribbean. November 2012.

#### Invited Seminars 

1. **Huffmyer AS**. Empowering Discovery: The Role of Education in Scientific Resilience. Speech to the Philanthropic Education Organization of Oregon. Seaside, OR, USA. May 2025.
2. **Huffmyer AS**. Understanding shifts in symbiotic and physiological state in reef-building corals across developmental and environmental gradients. Old Dominion University Biology Seminar Series. Virtual invited seminar speaker. December 2022.   
3. **Huffmyer AS**. Physiological and multi-omic signatures of shifts in symbiotic nutritional exchange in reef-building coral early life history. University of Technology Sydney Climate Change Cluster (C3). Virtual invited seminar speaker. June 2022.  

#### Poster Presentations 

1. **Huffmyer AS** and J Lemus. TA teaching styles impact student achievement in a research-based undergraduate science course. Society of Integrative and Comparative Biology. New Orleans, LA, USA. January 2017.
2. **Huffmyer AS**, H Putnam, RD Gates. Parental influence on patterns of growth and survivorship in juvenile Pocillopora damicornis corals exposed to thermal stress conditions. Western Society of Naturalists. Monterey Bay, CA, USA. November 2016.
3. **Huffmyer AS** and J Lemus. TA teaching styles impact student achievement in a research-based undergraduate science course. International Coral Reef Symposium. Honolulu, HI, USA. June 2016.
4. **Huffmyer AS**. Utilizing heterotrophy: Nutritional provisioning for juvenile corals in climate change. UHM Albert L. Tester Symposium. Honolulu, HI, USA. April 2016.

#### Presentations by Mentored Students

1. Buchanan G, **Huffmyer AS**, Roberts S. Effects of salinity and ocean acidification stress on Pacific oyster (Magallana gigas) thermal tolerance. University of Washington SAFS Undergraduate Capstone Symposium. June 2025. 
2. Baird M, **Huffmyer AS**, Roberts S. Application of metabolic assays to characterize thermal tolerance in Pacific Oyster (Magallana gigas) early life stages. University of Washington Undergradaute Research Symposium. Seattle, WA, USA. May 2025. Population Health Reconigtion Award. 
3. Elvrum C, Roberts S, **Huffmyer AS**. Analyzing oysters response to environmental stressors using a resazurin assay. University of Washington Louis Stokes Alliance for Minority Participation symposium. Seattle, WA, USA. August 2024.
4. Essington E, Roberts S, White S, **Huffmyer AS**. Environmental hardening in Pacific oysters across multiple life stages. University of Washington Department of Biology undergraudate research symposium. May 2024. 
5. Epps A, **AS Huffmyer**, RD Gates. Growth and survivorship in fused juvenile corals. 44th Tester Memorial Symposium. University of Hawaiʻi at Mānoa. Honolulu, HI, USA. April 2019. 
6. Katayama H, M Melamed, M Manning, **AS Huffmyer**. Parental influence on coral survivorship in warmer water temperatures. Kapiʻolani Community College. Honolulu, Hawaiʻi, USA. Spring 2018. 
7. Epps A, **AS Huffmyer**, RD Gates. Up, down, and all around: Growth patterns in reef-building corals. Western Society of Naturalists. Tacoma, WA, USA. November 2018. 
8. Johnson J, **AS Huffmyer**, RD Gates. The effects of feeding and temperature on juvenile coral survival. UHM course presentation. Honolulu, HI, USA. November 2017. 

:::

::: {.content-card}
# Mentorship

- 2025-2026: Undergraduate student supervised research, University of Washington (10+ students)	
- 2024: Graduate student mentor, University of Washington (5 students) 
- 2024: Undergraduate student mentor, University of Washington Louis Stokes Alliance for Minority Participation Program (2 students)
- 2020-2024: Graduate student mentor, University of Rhode Island (8 graduate students) 
- 2022-2024:Community member mentor, Moorea, French Polynesia (1 community member)
- 2016-2021: Undergraduate student mentor, University of Hawaiʻi at Mānoa (6 students)
- 2017-2018:	Hawaiʻi Institute of Marine Biology Community College Internship mentor (6 students)

#### Awards and Recognition in Mentorship

- 2019: University of Hawaiʻi at Mānoa Graduate Student Organization Award in Mentorship

:::

::: {.content-card}
# Teaching Experience 

#### Teaching Assistantships and Course Instruction 

- 2023: RNAseq: Experimental design and analytical approaches. University of Washington – Bioinformatics for Environmental Sciences (FSH546). Invited lecture (12 students). 
- 2023:	Proposal writing and scientific messaging. University of Washington - Graduate student professional development course (FSH512). Invited lecture (22 students)
- 2021:	Coral symbiosis and application of ‘omics to answer emerging questions in marine invertebrate ecophysiology. University of Rhode Island - Marine Environmental Physiology course. Virtual invited lecture (20 students) 
- 2018:	Early life history of reef building corals. University of Hawaiʻi at Mānoa - Corals and Coral Reefs course. Invited lecture. Honolulu, HI, USA (30 students)
- 2017: You are what you eat: Coral nutrition. University of Hawaiʻi at Mānoa - Corals and Coral Reefs course. Invited lecture. Honolulu, HI, USA (25 students)
- 2014-2015: University of Hawaiʻi at Manoa Biology 265 Laboratory Teaching Assistant (75 students)
- 2013, 2015: HIMB Summer Research Experience in Marine Biology for Hawaiʻi High School Students: Instructor and research mentor (40 students)

#### Curriculum Development 

- 2023: Maritime High School curriculum unit: Storytelling in scientific writing
- 2023: Maritime High School curriculum unit: Coastal erosion
- 2018: Stanford Ignite educator curriculum development co-host					
- 2016: Climate Science Teachers Institute co-coordinator, American Samoa & Marshall Islands
- 2015: COSEE Island Earth Traditional Hawaiian Knowledge curriculum co-coordinator	

:::

::: {.content-card}
# Leadership, Outreach, and Communication

#### Outreach and Science Communication 

- 2023-2025: Science Communication Advisor, Reva Atea education organization, Moorea French Polynesia
- 2023-2025: Editor, Fete de la Science La Revue Scientifique student journal, Moorea French Polynesia
- 2025: University of Washington SAFS Open House Public Outreach (>100 people)
- 2024: Outreach event and laboratory tour, Maritime High School 10th grade (35 students)
- 2024: Guest scientist presentation, REU-Blinks/DDCSP “Meet a Scientist” program
- 2023: University of Washington NSF GRFP workshop mentor 
- 2022-2023: E5 Rules of Life – Communication and Science Education committee member
- 2019: Waikīkī Aquarium Marine Educators Night volunteer (100+ attendees)			
- 2019: Judge at the Windward District High School Science Fair, Kāneʻohe, Hawaiʻi		
- 2015-2020: seaHarmony Collaboration Network blog series writer					
- 2018: National Academies of Science Interventions to Increase Reef Resilience workshop
- 2017: STEMplus program educator workshop coordinator 					
- 2015-2017: UHM Ocean Earth Sciences and Technology Open House volunteer (1000+ attendees)	

#### Broadening Participation 

- 2023-2025: AGU LANDInG Postdoctoral Research Fellowship Professional Development Program in Diversity, Equity, and Inclusion (3 years, 80+ hours)
- 2023: Pilina, Indigenous Literacy, and ʻĀina Momona: Healthy and Thriving Communities of People and Place; NOAA National Marine Sanctuaries Professional Development 
- 2021: Inclusive SciComm Conference		
- 2020: Society for Advancing Chicanos/Hispanics and Native Americans in Science Conference
- 2020: STEMS2 Hawaiʻi Knowledge Sharing Conference 		

#### Media Involvement 

- Scientific American, “How corals fight back against warming seas”. February 2025 
- Chemical and Engineering News, “Young coral beat the heat with metabolic rewiring”. November 2024
- 10+ media outlets,“Young corals use metabolic tricks to resist bleaching”. November 2024
- UH Mānoa SOEST News, “Student researchers improve coral restoration efforts”. March 2022
- Rhode Island Reporter, Brooke Wolfenbarger. “Saving Coral Reefs”. Scientific Advisor. March 2021
- NOVA PBS: “Reef Rescue”. Scientific Advisor. January 2021.
- Caravan Labs: “Lost cities: A story of coral”. Interactive Documentary. 2020. 
- CBC: “Reef Rescue”. Documentary. March 2020.
- Astrobites: “How TAs make a difference in the classroom”. Briley Lewis, UCLA. 2019. 
- Gizmodo: “How a Superheroic Breed of Coral could help save the reefs”. July 2018.
- Voice of the Sea: “Human Assisted Corals”. Episode 5-7. June 2018.
- NOVA PBS: “Decoding the Weather Machine”. April 2018.
- HBO Vice: “Rebuilding our Reefs”. Episode 5. September 2017. 
- Wavelengths Podcast: “Super Corals – Getting Ahead of Climate Change”. Episode 3. January 2018.

#### Leadership and Community Involvement 

- 2026: International Coral Reef Symposium session chair (Metabolic foundation of reef function)
- 2025: International Coral Reef Society Virtual Delegate United Nations Convention on Climate Change (COP29)
- 2022-2024: Scientific advisor - Reefs Unknown mesophotic reef research program
- 2021: University of Washington PhD Career Ladder Program
- 2018-2020: National Marine Educators Association conference planning committee member
- 2018-2019: 44th Annual UHM Albert Tester Memorial Student Symposium organizer
- 2015-2016: Graduate Women in Science Outreach Coordinator Officer	
:::

<hr class="section-divider">

::: {.content-card}
## Contact

##### Ariana S. Huffmyer, PhD 
Research Scientist  
School of Aquatic and Fishery Sciences  
University of Washington  

##### Email:  
[ashuff@uw.edu](mailto:ashuff@uw.edu)  

##### Mailing Address:  
1122 NE Boat St Rm 116  
Seattle, WA 98195  

##### Office Location:   
Fisheries Teaching & Research Building  
University of Washington  
Room 234  

---

### Find me online

- [GitHub](https://github.com/ahuffmyer)  
- [Google Scholar](https://scholar.google.co.uk/citations?user=_dw3pYEAAAAJ&hl=en&oi=ao)  
- [ResearchGate](https://www.researchgate.net/profile/Ariana-Huffmyer)  
- [ORCID](https://orcid.org/0000-0002-9170-0971)
- [Roberts Lab (UW)](https://faculty.washington.edu/sr320/) 

:::
