---
title: "September Goals and Daily Entries"
author: "Ariana Huffmyer"
date: "2026-09-21"
categories: [goals, daily-entries]
description: "September 2026 goals and daily entries"
image: ""
---

# Overview

Here are my goals and daily entries for September 2026.     

## Goals

### Writing and manuscripts 
              
1. Revise and resubmit PolyIC manuscript
2. Write intro and discussion of Hawaii 2023 paper
3. Start draft of Moorea 2023 paper (abstract, methods)
4. Start draft of Westcott oyster priming manuscript

### Grants

1. NSF IOS application with H. Putnam 

### Analysis

1. Moorea 2023 RNAseq 
2. Moorea 2023 metabolomics 

### Field and lab work 

1. Last time point checks at Sequim, Baywater (done), and Goose Point
2. Oyster image analysis for all 2026 summer outplants
3. El Nino experiment planning 

### Conferences 

1. Submit MCR AIM abstract for metabolomics and lipidomics 
2. ~~PCSGA talk~~ 

### Future publications to work on

1. E5 metabolomics/lipidomics manuscript  

## **Daily Log**   

### September 21 

- NSF grant with Hollie 
- Preparing for big week of field work and planning lab assays 

### September 14-18

- PCSGA conference week

### September 11

- El Nino pilot project set up
- PCSGA talk
- Meet with SR 
- Meet with ME

### September 10

- VIMS data
- PCSGA talk

### September 9

- Oyster mortality data analysis 
- VIMS data
- PCSGA talk

### September 8

- Oyster mortality data analysis 
- NSF grant with Hollie 

### September 1-4

- PolyIC manuscript revisions
- Manchester project survival assays 
- BIO Core grant with Putnam 
- PCSGA talk preparations 