---
title: "August Goals and Daily Entries"
author: "Ariana Huffmyer"
date: "2026-08-17"
categories: [goals, daily-entries]
description: "August 2026 goals and daily entries"
image: ""
---

# Overview

Here are my goals and daily entries for August 2026.     

## Goals

### Writing and manuscripts 
              
1. ~~Submit PolyIC paper and revise with qPCR data~~ 
2. Write intro and discussion of Hawaii 2023 paper
3. Start draft of Moorea 2023 paper (abstract, methods)
4. Start draft of Westcott oyster priming manuscript

### Grants

1. NSF IOS application with H. Putnam 

### Analysis

1. Moorea 2023 RNAseq 
2. Moorea 2023 metabolomics 

### Field and lab work 

1. Summer quick check ups at Sequim, Baywater, Westcott, and Goose Point
2. Oyster image analysis for all 2026 summer outplants
3. ~~Manchester hardening experiment final sampling~~ 
4. El Nino experiment planning 

### Future publications to work on

1. E5 metabolomics/lipidomics manuscript  

## **Daily Log**   

### August 18 

- On campus 
- Manchester survival 
- IOS writing 
- PCSGA talk  

### August 17 

- Manchester sampling management
- IOS grant
- Submitted PolyIC

### August 14 

- Manchester sampling day 

### August 13 

- PolyIC paper
- Manchester experiment planning
- IOS grant 

### August 12 

- PolyIC paper
- Manchester experiment planning
- IOS grant 

### August 11 

- PolyIC paper
- Manchester experiment planning
- Reimbursements for travel 
- IOS grant meeting with Hollie

### August 10 

- PolyIC paper
- Manchester experiment planning

### August 7 

- PolyIC paper
- Manchester experiment planning

### August 6 

- SICB symposium planning
- PolyIC paper

### August 5 

- PolyIC paper
- El Nino project design

### August 4 

- qPCR analysis data 
- PolyIC paper
- Meeting with Steven

### August 3 

- qPCR analysis data 
- Oyster image analysis 