---
title: "May Goals and Daily Entries"
author: "Ariana Huffmyer"
date: "2026-04-04"
categories: [goals, daily-entries]
description: "May 2026 goals and daily entries"
image: ""
---

# Overview

Here are my goals and daily entries for May 2026. I am returning from leave and this includes a list of the main projects I will start working on as I return to work. Bold projects are the things that are most critical.    

## Goals

### Writing and manuscripts 
              
1. **Revise resazurin paper (due end of June)**
2. **Revise E5 physiology paper (due end of June)**
3. Submit PolyIC paper and revise with resazurin citations
4. Full draft of Hawaii 2023 paper
5. Start draft of Moorea 2023 paper (abstract, methods)
6. Start draft of Westcott oyster priming manuscript

### Grants

1. NSF IOS application with H. Putnam 
2. ~~NSF OCE final report due May~~ 
3. Moore foundation grant

### Analysis

1. Moorea 2023 RNAseq 
2. Moorea 2023 metabolomics 

### Field and lab work 

1. Plan summer 2026 oyster outplants 
2. ~~Plan spring/summer assessments of current oyster outplants~~ 
3. ~~Conduct Goose Point assessment (May 22)~~
4. Conduct Baywater assessment (June 6)
5. Conduct Manchester assessment (May 28)
6. Conduct Sequim Bay assessment (May 31)

## **Daily Log**   

### May 26

- New hardening experiment planning 
- Poly IC paper planning 
- E5 revisions 
- Planning field assessments

### May 22

- Goose Point assessment

### May 21

- PeerJ resubmission
- E5 paper revisions

### May 20

- PeerJ resubmission
- E5 paper revisions
- Lab meeting

### May 19

- Meeting with Steven
- E5 revisions
- PeerJ revisions

### May 18

- Meeting with Lucy for COTS bioinformatics paper 
- Westcott deployment protocol 
- Resazurin manuscript

### May 5-17 

- Forgot to do daily entries! I worked on scheduling farm assessments, analyzing glycogen data, submitting NSF final report, and the resazurin manuscript 

### May 4

- NSF Final report
