---
title: "All Projects To Do List"
author: "Ariana Huffmyer"
date: "2026-01-01"
categories: [goals]
description: "To do list for all ongoing projects"
image: ""
---

# Overview

This post lists all my ongoing projects and to-do list.  

## Hawaii 2023   

**Writing**   

- Discussion
- Introduction

## Moorea 2023   

**Data collection and analysis**   

- Update methods section 
- ITS2 sequencing analysis
- RNAseq analysis
- Metabolomics analysis
- ITS2 sample sequencing for POC larvae? 

## E5 Physiology   

**In review**   

- Revise post review

## E5 Metabolism   

**Data analysis** 

- Metabolomics and lipidomics analysis for timeseries metabolism paper 

## E5 Nom Nom   

**Data analysis** 

- Analyze PR rates data set 

## Resazurin methods manuscript   

**In reivew** 

- Post review revisions

## Oyster 2024 Stress Hardening   

**Data collection and analysis** 

- *Goose Point*
	- Image analysis of Oct assessment [Noah]
  
- *Sequim* 
	- Conduct spring assessment

- *Baywater* 
	- Conduct spring assessment 

- *Westcott* 
	- Image analysis of Dec assessment [Grace]
	- Send data to Westcott [Grace]

- Westcott data paper writing

## SORMI Assay Development   

**Data collection**   

- Glycogen assays [Sam and Hazel]
- Guava Muse assays [Hazel]

## Manchester Hardening

**Data collection** 

- Spring assessment of lab performance (April)

## PolyIC Larvae   

**Full draft**   
 
- Submit to journal

## Planning and funding    

- IOS submission with Hollie (January 2026)
