---
title: "October Goals and Daily Entries"
author: "Ariana Huffmyer"
date: "2026-10-01"
categories: [goals, daily-entries]
description: "October 2026 goals and daily entries"
image: ""
---

# Overview

Here are my goals and daily entries for October 2026.     

## Goals

### Writing and manuscripts 
              
1. Revise and resubmit PolyIC manuscript
2. Write intro and discussion of Hawaii 2023 paper
3. Start draft of Moorea 2023 paper (abstract, methods)
4. Start draft of Westcott oyster priming manuscript

### Grants

1. NSF IOS application with H. Putnam 

### Analysis

1. Moorea 2023 RNAseq 
2. Moorea 2023 metabolomics 

### Field and lab work 

1. Oyster image analysis for all 2026 summer outplants
2. El Nino experiment planning 
3. Survival assays for all outplant experiments (10K DONE, Effort A, Effort E)

### Conferences 

1. Submit MCR AIM abstract for metabolomics and lipidomics 

### Future publications to work on

1. E5 metabolomics/lipidomics manuscript  

## **Daily Log**   

### October 5 

- Oyster survival assays 
- NSF 
- Reimbursements
- Grad student recommendation 

### October 4

- Oysters to campus 
- Started new survival trial

### October 2

- Goose Point assessment/close out day

### October 1

- Metabolomics meeting with Yaamini
- PolyIC revisions
- NSF grant