---
title: "January Goals and Daily Entries"
author: "Ariana Huffmyer"
date: "2026-01-26"
categories: [goals, daily-entries]
description: "January 2026 goals and daily entries"
image: ""
---

# Overview

January 2026 goals and daily notebook entries. 

## Goals

### Writing and manuscripts 
              
1. ~~Results for Mcap2023 analysis~~
2. Submit PolyIC paper 
3. Start Moorea 2023 paper (abstract, outline methods)
4. Draft of Westcott oyster priming manuscript

### Analysis

1. ~~Finalize Hawaii 2023 scripts and data sets~~
2. Moorea 2023 RNAseq and metabolomics data sets 

### Funding

1. Write IOS grant with HP

### Other

1. ~~ICRS abstract reviews~~ 
2. ~~Develop personal website~~ 

## **Daily Log**   

### January 26

- IOS proposal 

### January 23

- Travel to UW to drop off oysters
- Cleaned FTR tanks and reorganized oysters 

### January 22

- Travel to Sequim to pick up oysters

### January 21

- IOS proposal 
- UG project design 

### January 20

- IOS proposal 

### January 19

- IOS proposal 

### January 16

- IOS proposal 
- Undergraduate student projects
- Lab ordering
- E5 molecular meeting

### January 15

- IOS proposal 
- Undergraduate student projects
- Lab ordering

### January 14

- Metabolomics writing group 
- Hawaii 2023
- IOS proposal 

### January 13

- IOS proposal 
- Lab meeting 
- Hawaii 2023 

### January 12

- IOS proposal 
- Personal website development
- Hawaii 2023 writing 

### January 9

- IOS proposal 
- Hawaii 2023 ms 
- Job applications

### January 8

- IOS proposal 
- Hawaii 2023 ms 
- Planning projects with Noah O. 
- Image analysis

### January 7

- Onboarding with undergraduate student in lab 
- Manchester data analysis and updates 
- PolyIC manuscript
- Job application materials 
- Hawaii 2023 data 

### January 6

- Hawaii 2023 data analysis and writing results
- Meeting with Jen and Andrei
- Manchester field work 

### January 5

- Hawaii 2023 data analysis and writing results
- IOS proposal 
- Job applications 


