---
title: "Writing Project Status"
author: "Ariana Huffmyer"
date: "2026-01-01"
categories: [goals, writing]
description: "Status of my writing projects and manuscripts"
image: ""
---

# Overview

I have listed active manuscripts below and their status along with my writing goals!  

They are organized from "oldest" data sets to "newest" data sets.  

## E5 physiology 

*Status*: Submitted 

*Next step*: Revise post submission

*Timeline*: Pending 

## Hawaii2023

*Status*: Results finished

*Next step*: Write introduction and discussion sections

*Time line*: Finish draft following leave

## Moorea2023

*Status*: Draft of methods

*Next step*: Write methods, start RNAseq and metabolomics analysis

*Timeline*: Finish draft following leave 

## Resazurin paper 

*Status*: Submitted, pending review

*Next step*: Address review  

*Timeline*: Pending

## Oyster Hardening 

*Status*: Started a draft of Westcott data for potential paper

*Next step*: Write methods and results of Westcott paper

*Timeline*: Finish draft pending leave 

## PolyIC Larvae   

*Status*: On bioRxiv

*Next step*: Submit to journal

*Timeline*: Submit January 2026 

## Nom Nom Project   

*Status*: Data collection

*Next step*: Analyze PR data and work with collaborators on ITS2 data

*Timeline*: Pending metadata provided by HP 

## E5 metabolism 

*Status*: Data analysis

*Next step*: Analyze lipidomic and metabolomic data in context of physiology data

*Timeline*: Mid 2026 draft 

## Collaborative manuscripts 

This is a list of the papers (I think all of them) that I am a coauthor on at the moment:  

- Ashey et al. E5 ncRNA descriptive - **in review**
- Becker et al. Molecular mechanisms - **writing**
- Becker et al. Heatwave environmental memory - **writing**  
- Ashey et al. Mcap developmental RNAs - **writing** 
- Gorman et al. CoTS RNAseq = **analysis**  
- E5 group time series molecular - **analysis**
