---
title: "July Goals and Daily Entries"
author: "Ariana Huffmyer"
date: "2026-07-23"
categories: [goals, daily-entries]
description: "July 2026 goals and daily entries"
image: ""
---

# Overview

Here are my goals and daily entries for July 2026. Bold projects are the things that are most critical.   

## Goals

### Writing and manuscripts 
              
1. Submit PolyIC paper and revise with resazurin citations
2. Write discussion of Hawaii 2023 paper
3. Start full draft of Moorea 2023 paper (abstract, methods)
4. Start full draft of Westcott oyster priming manuscript

### Grants

1. NSF IOS application with H. Putnam 

### Analysis

1. Moorea 2023 RNAseq 
2. Moorea 2023 metabolomics 

### Field and lab work 

1. ~~July 2026 outplants at Westcott and hardening at Point Whitney~~ 
2. Summer quick check ups at Sequim, Baywater, and Goose Point
3. Check Westcott

### Future publications to work on

1. E5 metabolomics manuscript 

## **Daily Log**   

## July 23 

- Meeting with Yaamini
- Resazurin index analysis
- Peer review

## July 22 

- Poly IC paper
- Oyster image analysis 
- SORMI meeting

## July 21 

- Poly IC paper 
- Hazel meeting 
- Callie meeting

## July 20 

- Westcott data management
- New publications
- Oyster image analysis
- PolyIC paper

## July 16-18 

- Westcott travel and outplants

## July 15 

- Point Whitney and Westcott prep

## July 14 

- E5 proof
- SICB symposium organizing 

## July 13 

- Oyster image analysis protocol
- PolyIC paper
- E5 paper proof 

## July 7

- SR meeting
- Oyster image analysis repo and protocols
- Metabolomics writing meeting

## July 6

- Point Whitney hatchery trip and seed hardening

## July 2

- Manchester sampling and cleaning cages

## July 1

- Point Whitney hardening 
- Assembling growth and survival data for SHIELD 
