---
title: "Picking up new oyster seed for UW projects"
author: "Ariana Huffmyer"
date: "2026-01-21"
categories: [cgigas, oyster]
description: "Ordering and picking up new oyster seed for UW student projects"
image: ""
---

# Overview

This post details my process for ordering, picking up, and delivering new oyster seed from Jamestown Seafood to UW for student projects.  

## 1. Ordering seed 

I called for wholesale seed sales from Jamestown Seafood (contact information here)[https://jamestownseafood.com/#products] and spoke with Jamie. I requested the following seed via their oyster seed sales:  

- 2,000 seed at ~6 mm length ($36 per 1K)
- 2,000 seed at ~9 mm length ($47 per 1K)

Jamestown Seafood provided an invoice for a total cost of $180.78 that I will pay for with a personal check and submit for a UW reimbursement.   

## 2. Picking up seed 

I will pick up from the John Wayne Marina in Sequim, WA on Thursday January 22 and store the oysters in a cooler. The seed will stay at ~40-50°F overnight in the cooler.  

## 3. Transfer seed to UW 

Seed will then be transferred to UW (FTR tanks) on Friday January 23. In preparation for the transfer, Noah will be doing a full tank clean and water change in the left tank and removing all other oysters from that tank.  

On Friday, I will put the new oysters in their own new, clean tank in either mesh bags or the small mesh plastic cages. I'll then reassess the other oysters to see if we want to keep any of the older stocks.  

These oysters will then be used for UW student projects this quarter.  

The process was simple and easy and we can use wholesale seed for future projects as needed.  

